### ISSUE TITLE
Generate public documentation

### ISSUE THREAD

**Issue by liquuid** [subutai-io/ansible#6]
Is importante follow this guide 

http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html

**Comment by liquuid** [comment]
I followed all instructions and stuck in this error
```

PYTHONPATH=../../lib ../bin/plugin_formatter.py -t rst --template-dir=../templates --module-dir=../../lib/ansible/modules -o rst/module_docs/ 
Traceback (most recent call last):
  File "../bin/plugin_formatter.py", line 639, in <module>
    main()
  File "../bin/plugin_formatter.py", line 597, in main
    plugin_info, categories = get_plugin_info(options.module_dir, limit_to=options.limit_to, verbose=(options.verbosity > 0))
  File "../bin/plugin_formatter.py", line 239, in get_plugin_info
    doc, examples, returndocs, metadata = plugin_docs.get_docstring(module_path, fragment_loader, verbose=verbose)
  File "/home/liquuid/devel/ansible/lib/ansible/utils/plugin_docs.py", line 116, in get_docstring
    data = read_docstring(filename, verbose=verbose, ignore_errors=ignore_errors)
  File "/home/liquuid/devel/ansible/lib/ansible/parsing/plugin_docs.py", line 61, in read_docstring
    data[varkey] = AnsibleLoader(child.value.s, file_name=filename).get_single_data()
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/home/liquuid/devel/ansible/u16-env/local/lib/python2.7/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<string>", line 30, column 1:
    extends_documentation_fragment
    ^
could not find expected ':'
  in "<string>", line 33, column 1:
    author:
    ^
Makefile:86: recipe for target 'modules' failed
make[1]: *** [modules] Error 1
make[1]: Leaving directory '/home/liquuid/devel/ansible/docs/docsite'
Makefile:346: recipe for target 'webdocs' failed
make: *** [webdocs] Error 2
```
